### ISSUE TITLE
More paths for path libdrizzle path disocvery

### ISSUE THREAD

**Issue by splitice** [openresty/drizzle-nginx-module#23]
Ubuntu 12.04 (LTS) installs libdrizzle into ```/usr/lib/``` and ```/usr/include/libdrizzle-1.0```. By default the configure script does not search this path.

Could these be added?

If anyone stumbles accross this ticket with this problem the interim solution is to call configure prefixed with:
```
env LIBDRIZZLE_LIB=/usr/lib/ LIBDRIZZLE_INC=/usr/include/libdrizzle-1.0 [...]
```

**Comment by agentzh** [comment]
@splitice Will you contribute a patch to search this location combination? Thanks!

**Comment by splitice** [comment]
I'll see what I can do. Currently my focus is going to finishing off travis-ci integration for lua-nginx-module. So close in that regard :)

I have a question for you too in regards to Test::Nginx so I'll open that in a sec.

**Comment by splitice** [comment]
Never mind it was not particularly hard to patch & test. PR submitted.
